[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "20"

[[headers]]
for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
